# Generated by Django 5.2.1 on 2026-05-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=32)),
                ('activity_type', models.CharField(choices=[('fuel', 'Fuel'), ('electricity', 'Electricity'), ('procurement', 'Procurement'), ('flight', 'Flight'), ('hotel', 'Hotel'), ('ground_transport', 'Ground transport')], max_length=32)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=16)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=64)),
                ('normalized_unit', models.CharField(blank=True, default='', max_length=64)),
                ('spend_amount', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=16)),
                ('facility', models.CharField(blank=True, default='', max_length=255)),
                ('vendor', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('estimated_emissions_kgco2e', models.FloatField(blank=True, null=True)),
                ('source_reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('locked_for_audit', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.organization')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_activity', to='ingestion.rawrecord')),
            ],
            options={
                'verbose_name_plural': 'normalized activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('issue_type', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='normalization.normalizedactivity')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
                'unique_together': {('activity', 'issue_type')},
            },
        ),
    ]
